project_name: MyGeneratedApp

database:
  type: sqlite
  url: sqlite:///./app.db
  connect_args:
    check_same_thread: false
  echo: false
  # Example for PostgreSQL:
  # type: postgresql
  # url: postgresql://user:password@localhost/dbname
  # connect_args: {}
  # echo: true

models:
  - name: User
    fields:
      - name: id
        type: Integer
        primary_key: true
        nullable: false
      - name: username
        type: String
        unique: true
        nullable: false
      - name: email
        type: String
        unique: true
        nullable: true
  - name: Post
    fields:
      - name: id
        type: Integer
        primary_key: true
        nullable: false
      - name: title
        type: String
        nullable: false
      - name: content
        type: String
        nullable: true
      - name: user_id
        type: Integer
        foreign_key: "user.id"
        nullable: false
endpoints:
  - model: User
    methods: [GET, POST, PUT, DELETE]
