database:
  type: postgresql
  url: postgresql://user:password@localhost:5432/mydb
  connect_args:
    sslmode: disable
  echo: true

models:
  - name: User
    fields:
      - name: id
        type: Integer
        primary_key: true
        nullable: false
      - name: username
        type: String
        unique: true
        nullable: false
      - name: email
        type: String
        unique: true
        nullable: true
  - name: Post
    fields:
      - name: id
        type: Integer
        primary_key: true
        nullable: false
      - name: title
        type: String
        nullable: false
      - name: content
        type: String

endpoints:
  - model: User
    methods: [create, read, update, delete]
  - model: Post
    methods: [create, read, update, delete]
